apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: byc6tu8kh-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/byc6tu8kh-dotnet-basic-gitops